#!/usr/bin/env bash
# Best School, bad luck, good luck
i=0
while [ $i -lt 9 ]
do
        echo Best School
        ((i++))
if [ $i = 3 ]
then echo 'bad luck'
elif [ $i = 7 ]
then echo 'good luck'
fi
done
